export enum ServiceOrderStatus {
    RECEIVED = 'RECEIVED',
    IN_DIAGNOSIS = 'IN_DIAGNOSIS',
    WAITING_FOR_APPROVAL = 'WAITING_FOR_APPROVAL',
    APPROVED = 'APPROVED',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED',
    DELIVERED = 'DELIVERED',

    CANCELLED = 'CANCELLED'
}
